## Inicio Python


In [ ]:
help()


Welcome to Python 3.7's help utility!

If this is your first time using Python, you should definitely check out
the tutorial on the Internet at https://docs.python.org/3.7/tutorial/.

Enter the name of any module, keyword, or topic to get help on writing
Python programs and using Python modules.  To quit this help utility and
return to the interpreter, just type "quit".

To get a list of available modules, keywords, symbols, or topics, type
"modules", "keywords", "symbols", or "topics".  Each module also comes
with a one-line summary of what it does; to list the modules whose name
or summary contain a given string such as "spam", type "modules spam".

help> 

You are now leaving help and returning to the Python interpreter.
If you want to ask for help on a particular object directly from the
interpreter, you can type "help(object)".  Executing "help('string')"
has the same effect as typing a particular string at the help> prompt.


In [ ]:
dir(str)

['__add__',
 '__class__',
 '__contains__',
 '__delattr__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getnewargs__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__iter__',
 '__le__',
 '__len__',
 '__lt__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmod__',
 '__rmul__',
 '__setattr__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 'capitalize',
 'casefold',
 'center',
 'count',
 'encode',
 'endswith',
 'expandtabs',
 'find',
 'format',
 'format_map',
 'index',
 'isalnum',
 'isalpha',
 'isascii',
 'isdecimal',
 'isdigit',
 'isidentifier',
 'islower',
 'isnumeric',
 'isprintable',
 'isspace',
 'istitle',
 'isupper',
 'join',
 'ljust',
 'lower',
 'lstrip',
 'maketrans',
 'partition',
 'replace',
 'rfind',
 'rindex',
 'rjust',
 'rpartition',
 'rsplit',
 'rstrip',
 'split',
 'splitlines',
 'startswith',
 'strip',
 'swapcase',
 'title',
 'translate',
 'upper',


In [ ]:
from random import randint
randomint = randint(1,100)
print(randomint)

75


In [ ]:
import random
randomint = random.randint(1,100)
print(randomint)

65


## Variables, operadores y tipos de Datos

In [ ]:
x = 100
print(x)
print(type(x))

100
<class 'int'>


In [ ]:
x = 'Hola Mundo'
print(x)
print(type(x))

Hola Mundo
<class 'str'>


In [ ]:
x = 10.0
print(x)
print(type(x))

10.0
<class 'float'>


In [ ]:
x = True
print(x)
print(type(x))

True
<class 'bool'>


In [ ]:
print(5/2)

2.5


In [ ]:
print(5//2)

2


In [ ]:
print(5%2)

1


In [ ]:
print(5**2)

25


In [ ]:
IntegerVar = 10
IntegerVar += 10
print(IntegerVar)

20


In [ ]:
StringVar = 'Deep'
StringVar += ' Learning'
print(StringVar)

Deep Learning


In [ ]:
IntegerVar, StringVar = StringVar, IntegerVar
print(IntegerVar)
print(StringVar)

Deep Learning
20


## Tipos de estructuras de datos

In [ ]:
x = [5, 'Hello', 1.8]
print(x)

[5, 'Hello', 1.8]


In [ ]:
len(x)

3

In [ ]:
x.append(100)
print(x)

[5, 'Hello', 1.8, 100, 100]


In [ ]:
x.remove(100)
print(x)

In [ ]:
print(len(x))

4


In [ ]:
x[1] = 'Deep'
print(x)

[5, 'Deep', 1.8, 100]


In [ ]:
y = [2.1, 'Learning']
z = x + y
print(z)

[5, 'Deep', 1.8, 100, 2.1, 'Learning']


## Indexacioón


* Lista (mutables o variables)

In [ ]:
x = [5, 'Deep', 1.8]
print("Primer elemento ----> x[0]: ", x[0])
print("Segundo elemento ----> x[1]: ", x[1])
print("Último elemento ----> x[-1]: ", x[-1])
print("Penúltimo elemento ----> x[-2]: ", x[-2])

Primer elemento ----> x[0]:  5
Segundo elemento ----> x[1]:  Deep
Último elemento ----> x[-1]:  1.8
Penúltimo elemento ----> x[-2]:  Deep


In [ ]:
print("Todos lo índices        ------>           ")
print("x[:]: ", x[:])
print("Índice 1 al final de la Lista        ------>           ")
print("x[1:]: ", x[1:])
print("Índice 1 al índice 2 (sin incluír el índice)       ------>           ")
print("x[1:2]: ", x[1:2])
print("Índice 0 al último índice (sin incluir el último)       ------>           ")
print("x[:-1]: ", x[:-1])

Todos lo índices        ------>           
x[:]:  [5, 'Deep', 1.8]
Índice 1 al final de la Lista        ------>           
x[1:]:  ['Deep', 1.8]
Índice 1 al índice 2 (sin incluír el índice)       ------>           
x[1:2]:  ['Deep']
Índice 0 al último índice (sin incluir el último)       ------>           
x[:-1]:  [5, 'Deep']


* Tuplas (no se pueden modificar su contenido una vez creadas)


In [ ]:
x = (1, "Deep", 3)
print(x)
print(x[1])

(1, 'Deep', 3)
Deep


In [ ]:
x = x + (4, 'Learning')
print(x)
print(x[-1])

(1, 'Deep', 3, 4, 'Learning')
Learning


* Diccionarios

In [ ]:
persona = {'nombre':'Jordi Torres',
           'profesion':'Profesor'}

print(persona)
print(persona['nombre'])
persona['profesion']

{'nombre': 'Jordi Torres', 'profesion': 'Profesor'}
Jordi Torres


'Profesor'

In [ ]:
persona['profesion'] = 'Investigador'
print(persona)

{'nombre': 'Jordi Torres', 'profesion': 'Investigador'}


In [ ]:
persona['grupo'] = 24
print(persona)

{'nombre': 'Jordi Torres', 'profesion': 'Investigador', 'grupo': 24}


In [ ]:
print(len(persona))

3


## Sentencias de control de flujo

* If

In [ ]:
x = 6.5
if x < 5:
  puntuacion = 'baja'
elif x <= 7:  #elif = else if
  puntuacion = 'media'
else:
  puntuacion = 'alta'
print(puntuacion)

media


In [ ]:
x = True
if x:
  print('Se da la condición')

Se da la condición


In [ ]:
a = 20
if a >= 22:
  print("Paris")
elif a <= 21:
  print("Barcelona")

Barcelona


In [ ]:
#If comprimido
b = 1
print("Paris" if b >= 92 else "Barcelona")

Barcelona


## Bucle for

In [ ]:
for a in range(1, 4):
  print(a)

1
2
3


In [ ]:
universidades = ["UPC", "UPM", "UPV"]
for universidad in universidades:
  print(universidad)

UPC
UPM
UPV


In [ ]:
for universidad in universidades:
  if universidad == "UPM":
    break
  print(universidad)

UPC


In [ ]:
for universidad in universidades:
  if universidad == "UPM":
    continue
  print(universidad)

UPC
UPV


## Bucle while

In [ ]:
x = 3
while x > 0:
  x = x + 1
  print(x)

## Funciones

In [ ]:
def mi_universidad(universidad = "UPC"):
  y = "Mi Universidad es la " + universidad
  return(y)

In [ ]:
print(mi_universidad("UPM"))

Mi Universidad es la UPM


In [ ]:
print(mi_universidad(universidad = "UPV"))

Mi Universidad es la UPV


In [ ]:
print(mi_universidad())

Mi Universidad es la UPC


In [ ]:
print(mi_universidad)

<function mi_universidad at 0x7f3a6668b3b0>


In [ ]:
def foo():
  a, b = 4, 5
  return a, b

In [ ]:
foo()

(4, 5)

## Funciones lambda

In [ ]:
fibonacci = (lambda x:1 if x <= 2 else fibonacci(x - 1) + fibonacci (x-2))

In [ ]:
fibonacci(10)

55

In [ ]:
suma = (lambda x: x + 45)
suma(30)

75

## Clases

In [ ]:
class Calculadora(object):
  '''Clase de una calculadora'''
  def __init__(self):
    """Inicíaliza la clase calculadora"""
    self.valor = 0

  def suma (self, n):
    """Suma un número n al valor"""
    self.valor +=n
  def getValor(self):
    """Obtiene el valor """
    return self.valor

In [ ]:
calc = Calculadora()

In [ ]:
calc.suma(2)

In [ ]:
print(calc.getValor())

2


In [ ]:
calc.suma(2)

In [ ]:
print(calc.getValor())

4


## Iterador

In [ ]:
vec = [1, 2, 3]
it = iter(vec)

next(it)

1

In [ ]:
next(it)

2

In [ ]:
next(it)

3

In [ ]:
type(vec)

list

In [ ]:
type(it)

list_iterator

## Decoradores

In [ ]:
def voy_a_imprimir_Hola():
  print("Hola")


voy_a_imprimir_Hola()

Hola


In [ ]:
def voy_a_imprimir_Hola():
  print("Hola")

def my_decorator(func):
  def wrapper():
    print("[Aviso: voy a decir algo]")
    func()
    print("[Aviso: ya he dicho algo]")
  return wrapper 

voy_a_imprimir_Hola = my_decorator(voy_a_imprimir_Hola)

In [ ]:
voy_a_imprimir_Hola()

[Aviso: voy a decir algo]
Hola
[Aviso: ya he dicho algo]


In [ ]:
voy_a_imprimir_Hola = my_decorator(voy_a_imprimir_Hola)

In [ ]:
@my_decorator
def voy_a_imprimir_Hola():
  print("Hola")

In [ ]:
voy_a_imprimir_Hola()

[Aviso: voy a decir algo]
Hola
[Aviso: ya he dicho algo]


## Libreria NumPY y Tensores.

In [ ]:
# array multidemsional llamada tensor --> estructura de datos
# Número de ejes.
# Forma.
# Tipos de Datos.

* Escalar o Tensor 0D

In [ ]:
import numpy as np

x = np.array(8)
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)

x:  8
x ndim:  0
x shape: ()
x size:  1
x dtype:  int64


* Vector o Tensor 1D

In [ ]:
x = np.array([2.3, 4.2, 3.3, 1.8])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)  #observe el tipo de datos flotante

x:  [2.3 4.2 3.3 1.8]
x ndim:  1
x shape: (4,)
x size:  4
x dtype:  float64


* Matrix o tensor de 2D

In [ ]:
x = np.array([[1, 2, 3],[4, 5, 6],[7, 8, 9]])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)  

x:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
x ndim:  2
x shape: (3, 3)
x size:  9
x dtype:  int64


* Para un Tensor 3D

In [ ]:
x = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print("x: ", x)
print("x ndim: ", x.ndim)
print("x shape:", x.shape)
print("x size: ", x.size)
print("x dtype: ", x.dtype)  

x:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
x ndim:  3
x shape: (2, 2, 2)
x size:  8
x dtype:  int64


* Funciones NumPy

In [ ]:
print("np.zeros((3,3): \n", np.zeros((3,3)))

np.zeros((3,3): 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
print("np.ones((3,3)): \n", np.ones((3,3)))

np.ones((3,3)): 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
print("np.eyes((3)): (identify matrix)\n", np.eye((3)))

np.eyes((3)): (identify matrix)
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [ ]:
print("np.random((3,3): \n", np.random.random((3,3)))

np.random((3,3): 
 [[0.18075151 0.69253208 0.60897886]
 [0.09310006 0.69508018 0.74111252]
 [0.18788873 0.61450727 0.30891434]]


## Manipulación de los tensores

In [ ]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print("x columna 1:", x[:,1])
print("x fila 0:", x[0,:])
print("x filas 0, 1 y columnas 1,2: \n", x[0:2, 1:3])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
x columna 1: [ 2  6 10]
x fila 0: [1 2 3 4]
x filas 0, 1 y columnas 1,2: 
 [[2 3]
 [6 7]]


In [ ]:
a = np.array([[1,2,3],[4,5,6]], dtype = np.int32)
b = np.array([[7,8],[9,10],[11,12]], dtype = np.int32)
c = a.dot(b)
print(f"{a.shape} * {b.shape} = {c.shape}")
print(c)

(2, 3) * (3, 2) = (2, 2)
[[ 58  64]
 [139 154]]


In [ ]:
x = np.array([[1,2,3,4,5,6]])
print(x)
print("x.shape: ", x.shape)
y = np.reshape(x, (2,3))
print("y: \n",y)
print("y.shape: ", y.shape)
z = np.reshape(x, (2,-1))
print("z: \n", z)
print("z.shape: ",z.shape)

[[1 2 3 4 5 6]]
x.shape:  (1, 6)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)
z: 
 [[1 2 3]
 [4 5 6]]
z.shape:  (2, 3)


In [ ]:
x = np.array([[1,2,3],[4,5,6]])
print("x: \n", x)
print("x.shape: ", x.shape)
y = np.expand_dims(x, 1)
print("y: \n", y)
print("y.shape ", y.shape)

x: 
 [[1 2 3]
 [4 5 6]]
x.shape:  (2, 3)
y: 
 [[[1 2 3]]

 [[4 5 6]]]
y.shape  (2, 1, 3)


In [ ]:
x = np.array([[[1, 2,3]],[[4, 5, 6]]])
print("x: \n", x)
print("x.shape: ", x.shape)
y = np.squeeze(x, 1) #estrujar dim 1
print("y: \n", y)
print("y.shape: ",y.shape)

x: 
 [[[1 2 3]]

 [[4 5 6]]]
x.shape:  (2, 1, 3)
y: 
 [[1 2 3]
 [4 5 6]]
y.shape:  (2, 3)


In [ ]:
#Valor máximo en un tensor
x = np.array([1,2,3,4])
print(x)

print(np.argmax(x))
print(np.max(x))

[1 2 3 4]
3
4


In [ ]:
x = np.array([1,2,4,4])
print(x)

print(np.argmax(x))
print(np.max(x))

[1 2 4 4]
2
4


In [ ]:
x = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(x)
print(np.argmax(x))
print(np.max(x))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
11
12


In [ ]:
print(np.argmax(x, axis = 0))
print(np.max(x, axis = 0))

print(np.argmax(x, axis = 1))
print(np.max(x, axis = 1))

[2 2 2 2]
[ 9 10 11 12]
[3 3 3]
[ 4  8 12]
